# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbHEAChghAKclT5lSzv-NhqAbCYoaohq
"""

import joblib
import sklearn
from train import messtovec, data_prep