# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbHEAChghAKclT5lSzv-NhqAbCYoaohq
"""

import joblib
import sklearn
import pandas as pd
from train import data_prep
filename = "best_model.joblib"
best_model = joblib.load(filename)

def score(text:str, model, threshold:float):
    k = {'message': [text]}
    testing_data = pd.DataFrame(k)
    te_d,te_i,te_c = data_prep(testing_data)
    testing_X = pd.DataFrame(data = te_d, 
                    index = te_i, 
                    columns = te_c)
    propensity = ((model.predict_proba(testing_X)).tolist())[0][1]
    if propensity >= threshold:
        prediction = 1
    else:
        prediction = 0
    return prediction, propensity

